-- MySQL Script generated by MySQL Workbench
-- Thu Aug 29 21:11:36 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema avras
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema avras
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `avras` DEFAULT CHARACTER SET utf8 ;
USE `avras` ;

-- -----------------------------------------------------
-- Table `avras`.`mandado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avras`.`mandado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `resumo` TINYTEXT NULL,
  `data_inicio` DATE NOT NULL,
  `data_fim` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avras`.`tipo_cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avras`.`tipo_cargo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `permissao` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avras`.`cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avras`.`cargo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `mandado_id` INT NOT NULL,
  `pessoa_id` INT NOT NULL,
  `tipo_cargo_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `MANDADO_CARGO_idx` (`mandado_id` ASC) VISIBLE,
  INDEX `PESSOA_CARGO_idx` (`pessoa_id` ASC) VISIBLE,
  INDEX `TIPO_CARGO_CARGO_idx` (`tipo_cargo_id` ASC) VISIBLE,
  CONSTRAINT `MANDADO_CARGO`
    FOREIGN KEY (`mandado_id`)
    REFERENCES `avras`.`mandado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `PESSOA_CARGO`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `avras`.`pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `TIPO_CARGO_CARGO`
    FOREIGN KEY (`tipo_cargo_id`)
    REFERENCES `avras`.`tipo_cargo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avras`.`pendencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avras`.`pendencia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NULL,
  `data_solicitacao` DATETIME NOT NULL,
  `data_deferimento` DATETIME NULL,
  `cargo_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `SOCIEDADE_CARGO_idx` (`cargo_id` ASC) VISIBLE,
  CONSTRAINT `SOCIEDADE_CARGO`
    FOREIGN KEY (`cargo_id`)
    REFERENCES `avras`.`cargo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avras`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avras`.`pessoa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `telefone` VARCHAR(14) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(32) NOT NULL,
  `socio` TINYINT NOT NULL DEFAULT 0,
  `jogador` TINYINT NOT NULL DEFAULT 0,
  `isento` TINYINT NOT NULL DEFAULT 0,
  `observacoes` VARCHAR(240) NULL,
  `pendencia_id` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  INDEX `PENDENCIA_PESSOA_idx` (`pendencia_id` ASC) VISIBLE,
  CONSTRAINT `PENDENCIA_PESSOA`
    FOREIGN KEY (`pendencia_id`)
    REFERENCES `avras`.`pendencia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avras`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avras`.`endereco` (
  `pessoa_id` INT NOT NULL,
  `cep` VARCHAR(10) NOT NULL,
  `cidade` VARCHAR(30) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `rua` VARCHAR(45) NOT NULL,
  `numero` INT NOT NULL,
  `complemento` VARCHAR(45) NULL,
  PRIMARY KEY (`pessoa_id`),
  INDEX `ENDERECO_PESSOA_idx` (`pessoa_id` ASC) VISIBLE,
  CONSTRAINT `ENDERECO_PESSOA`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `avras`.`pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avras`.`tipo_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avras`.`tipo_produto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(25) NOT NULL,
  `src_imagem` VARCHAR(80) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avras`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avras`.`produto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(25) NOT NULL,
  `valor_venda` DECIMAL(8,2) NOT NULL,
  `disponível` TINYINT NOT NULL DEFAULT 1,
  `estoque` INT NOT NULL,
  `estoque_minimo` INT NOT NULL,
  `categoria_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `PRODUTO_CATEGORIA_idx` (`categoria_id` ASC) VISIBLE,
  CONSTRAINT `PRODUTO_CATEGORIA`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `avras`.`tipo_produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avras`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avras`.`venda` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pessoa_id` INT NULL,
  `data_venda` DATETIME NOT NULL,
  `cargo_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `VENDA_PESSOA_idx` (`pessoa_id` ASC) VISIBLE,
  INDEX `VENDA_CARGO_idx` (`cargo_id` ASC) VISIBLE,
  CONSTRAINT `VENDA_PESSOA`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `avras`.`pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `VENDA_CARGO`
    FOREIGN KEY (`cargo_id`)
    REFERENCES `avras`.`cargo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avras`.`itens_venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avras`.`itens_venda` (
  `produto_id` INT NOT NULL,
  `venda_id` INT NOT NULL,
  `quantidade` INT NOT NULL,
  `produto_valor_unitario` DECIMAL(8,2) NOT NULL,
  PRIMARY KEY (`produto_id`, `venda_id`),
  INDEX `fk_produto_has_venda_venda1_idx` (`venda_id` ASC) VISIBLE,
  INDEX `fk_produto_has_venda_produto1_idx` (`produto_id` ASC) VISIBLE,
  CONSTRAINT `fk_produto_has_venda_produto1`
    FOREIGN KEY (`produto_id`)
    REFERENCES `avras`.`produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto_has_venda_venda1`
    FOREIGN KEY (`venda_id`)
    REFERENCES `avras`.`venda` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avras`.`sociedade_tempo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avras`.`sociedade_tempo` (
  `id` INT NOT NULL,
  `data_inicio` DATE NOT NULL,
  `data_fim` DATE NULL,
  `pessoa_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `PESSOA_SOCIEDADE_idx` (`pessoa_id` ASC) VISIBLE,
  CONSTRAINT `PESSOA_SOCIEDADE`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `avras`.`pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avras`.`tipo_patrimonio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avras`.`tipo_patrimonio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(90) NOT NULL,
  `descricao` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avras`.`patrimonio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avras`.`patrimonio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(80) NULL,
  `quantidade` INT NOT NULL,
  `valor_compra` DECIMAL(8,2) NULL,
  `valor_perda` DECIMAL(8,2) NULL,
  `disponibilidade` TINYINT NOT NULL,
  `anotacao` VARCHAR(80) NULL,
  `data_aquisicao` DATE NULL,
  `data_perda` DATE NULL,
  `tipo_patrimonio_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `TIPO_PATRIMONIO_ID_idx` (`tipo_patrimonio_id` ASC) VISIBLE,
  CONSTRAINT `TIPO_PATRIMONIO_ID`
    FOREIGN KEY (`tipo_patrimonio_id`)
    REFERENCES `avras`.`tipo_patrimonio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avras`.`caixa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avras`.`caixa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `valor` DECIMAL(8,2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avras`.`controle_caixa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avras`.`controle_caixa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `caixa_id` INT NOT NULL,
  `descricao` VARCHAR(120) NULL,
  `data_abertura` DATETIME NOT NULL,
  `data_fechamento` DATETIME NULL,
  `valor_abertura` DECIMAL(8,2) NOT NULL,
  `valor_fechamento` DECIMAL(8,2) NULL,
  `pessoa_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `CAIXA_ABERTURA_idx` (`caixa_id` ASC) VISIBLE,
  INDEX `PESSOA_CONTROLE_idx` (`pessoa_id` ASC) VISIBLE,
  CONSTRAINT `CAIXA_ABERTURA`
    FOREIGN KEY (`caixa_id`)
    REFERENCES `avras`.`caixa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `PESSOA_CONTROLE`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `avras`.`pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avras`.`movimentacao_caixa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avras`.`movimentacao_caixa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `motivo` VARCHAR(160) NOT NULL,
  `data` DATETIME NOT NULL,
  `valor` DECIMAL(8,2) NOT NULL,
  `cargo_id` INT NOT NULL,
  `caixa_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `CARGO_RETIRADA_idx` (`cargo_id` ASC) VISIBLE,
  INDEX `CAIXA_RETIRADA_idx` (`caixa_id` ASC) VISIBLE,
  CONSTRAINT `CARGO_RETIRADA`
    FOREIGN KEY (`cargo_id`)
    REFERENCES `avras`.`cargo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `CAIXA_RETIRADA`
    FOREIGN KEY (`caixa_id`)
    REFERENCES `avras`.`caixa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avras`.`tipo_conta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avras`.`tipo_conta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avras`.`tipo_aluguel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avras`.`tipo_aluguel` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `valor` DECIMAL(8,2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avras`.`aluguel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avras`.`aluguel` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pessoa_id` INT NOT NULL,
  `tipo_aluguel_id` INT NOT NULL,
  `data_solicitacao` DATE NOT NULL,
  `data_reserva` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `USUARIO_ALUGUEL_idx` (`pessoa_id` ASC) VISIBLE,
  INDEX `TIPO_ALUGUEL_idx` (`tipo_aluguel_id` ASC) VISIBLE,
  CONSTRAINT `USUARIO_ALUGUEL`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `avras`.`pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `TIPO_ALUGUEL`
    FOREIGN KEY (`tipo_aluguel_id`)
    REFERENCES `avras`.`tipo_aluguel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avras`.`conta_corrente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avras`.`conta_corrente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `valor` DECIMAL(8,2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avras`.`conta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avras`.`conta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(60) NULL,
  `valor` DECIMAL(8,2) NOT NULL,
  `data` DATE NOT NULL,
  `tipo_id` INT NOT NULL,
  `conta_corrente_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `TIPO_CONTA_idx` (`tipo_id` ASC) VISIBLE,
  INDEX `CONTA_CORRENTE_idx` (`conta_corrente_id` ASC) VISIBLE,
  CONSTRAINT `TIPO_CONTA`
    FOREIGN KEY (`tipo_id`)
    REFERENCES `avras`.`tipo_conta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `CONTA_CORRENTE`
    FOREIGN KEY (`conta_corrente_id`)
    REFERENCES `avras`.`conta_corrente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avras`.`pagar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avras`.`pagar` (
  `conta_id` INT NOT NULL,
  `valor_pago` DECIMAL(8,2) NULL,
  `data_pagamento` DATE NULL,
  `parcelas` INT NOT NULL,
  INDEX `CONTA_PAGAR_idx` (`conta_id` ASC) VISIBLE,
  PRIMARY KEY (`conta_id`),
  CONSTRAINT `CONTA_PAGAR`
    FOREIGN KEY (`conta_id`)
    REFERENCES `avras`.`conta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avras`.`patrocinadores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avras`.`patrocinadores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `data_cadastro` DATE NOT NULL,
  `valor` DECIMAL(8,2) NOT NULL,
  `parcelas` INT NOT NULL,
  `src_imagem` VARCHAR(80) NULL,
  `descricao` VARCHAR(80) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avras`.`receber`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avras`.`receber` (
  `conta_id` INT NOT NULL AUTO_INCREMENT,
  `data_recebimento` DATE NULL,
  `valor_recebimento` DECIMAL(8,2) NULL,
  `isento` TINYINT NOT NULL,
  `aluguel_id` INT NULL,
  `venda_id` INT NULL,
  `patrocinio_id` INT NULL,
  `pessoa_id` INT NULL,
  `controle_id` INT NULL,
  INDEX `CONTA_RECEBER_idx` (`conta_id` ASC) VISIBLE,
  INDEX `ALUGUEL_RECEBER_idx` (`aluguel_id` ASC) VISIBLE,
  INDEX `VENDA_RECEBER_idx` (`venda_id` ASC) VISIBLE,
  PRIMARY KEY (`conta_id`),
  INDEX `PATROCINADOR_RECEBER_idx` (`patrocinio_id` ASC) VISIBLE,
  INDEX `PESSOA_RECEBER_idx` (`pessoa_id` ASC) VISIBLE,
  INDEX `CONTROLE_RECEBER_idx` (`controle_id` ASC) VISIBLE,
  CONSTRAINT `CONTA_RECEBER`
    FOREIGN KEY (`conta_id`)
    REFERENCES `avras`.`conta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ALUGUEL_RECEBER`
    FOREIGN KEY (`aluguel_id`)
    REFERENCES `avras`.`aluguel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `VENDA_RECEBER`
    FOREIGN KEY (`venda_id`)
    REFERENCES `avras`.`venda` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `PATROCINADOR_RECEBER`
    FOREIGN KEY (`patrocinio_id`)
    REFERENCES `avras`.`patrocinadores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `PESSOA_RECEBER`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `avras`.`pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `CONTROLE_RECEBER`
    FOREIGN KEY (`controle_id`)
    REFERENCES `avras`.`controle_caixa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avras`.`compra_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avras`.`compra_produto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `valor_compra` DECIMAL(8,2) NOT NULL,
  `quantidade` VARCHAR(45) NOT NULL,
  `data_compra` DATETIME NOT NULL,
  `produto_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `PRODUTO_COMPRA_idx` (`produto_id` ASC) VISIBLE,
  CONSTRAINT `PRODUTO_COMPRA`
    FOREIGN KEY (`produto_id`)
    REFERENCES `avras`.`produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avras`.`movimentacao_conta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avras`.`movimentacao_conta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `motivo` VARCHAR(45) NOT NULL,
  `data` DATETIME NOT NULL,
  `valor` DECIMAL(8,2) NOT NULL,
  `cargo_id` INT NOT NULL,
  `conta_corrente_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `CARGO_MOVIMENTACAO_idx` (`cargo_id` ASC) VISIBLE,
  INDEX `MOVIMENTACAO_CONTACORRENTE_idx` (`conta_corrente_id` ASC) VISIBLE,
  CONSTRAINT `CARGO_MOVIMENTACAO`
    FOREIGN KEY (`cargo_id`)
    REFERENCES `avras`.`cargo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `MOVIMENTACAO_CONTACORRENTE`
    FOREIGN KEY (`conta_corrente_id`)
    REFERENCES `avras`.`conta_corrente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
